# Generated by Django 4.2.4 on 2023-09-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_productconfig_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/product/')),
            ],
        ),
        migrations.AddField(
            model_name='productconfig',
            name='files',
            field=models.ManyToManyField(to='dashboard.feedfile'),
        ),
    ]
