# Generated by Django 4.2.4 on 2023-09-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_feedfile_productconfig_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productconfig',
            name='files',
        ),
        migrations.AddField(
            model_name='productconfig',
            name='file_1',
            field=models.FileField(null=True, upload_to='static/product/'),
        ),
        migrations.AddField(
            model_name='productconfig',
            name='file_2',
            field=models.FileField(null=True, upload_to='static/product/'),
        ),
        migrations.AddField(
            model_name='productconfig',
            name='file_3',
            field=models.FileField(null=True, upload_to='static/product/'),
        ),
    ]
