# Generated by Django 4.2.4 on 2023-09-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_productconfig_files_productconfig_file_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconfig',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
    ]
