# Generated by Django 4.2.4 on 2023-09-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_productconfig_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconfig',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='static/product/'),
        ),
        migrations.AlterField(
            model_name='productconfig',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='static/product/'),
        ),
        migrations.AlterField(
            model_name='productconfig',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='static/product/'),
        ),
    ]
