# Generated by Django 4.2.4 on 2023-09-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_productconfig_file_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productconfig',
            name='intent',
        ),
    ]
